
import React from 'react';
import { ShoppingBag, Home, CheckSquare, Users, User, Wallet as WalletIcon } from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    welcome: 'Welcome to Priyaadarsh',
    vision: 'Our Vision: Empowering Every Indian with Financial Freedom.',
    services: 'Services: Shopping, Investments, Tasks, and more.',
    register: 'Register',
    login: 'Login',
    name: 'Full Name',
    emailLabel: 'Email Address',
    mobile: 'Mobile Number',
    referralId: 'Referrer ID',
    referrerName: 'Referrer Name',
    password: 'Password (12 digits)',
    pin: 'Transaction PIN (4 digits)',
    deposit: 'Deposit',
    balanceWallet: 'Balance Wallet',
    coinWallet: 'Coin Wallet',
    redeem: 'Redeem (50,000 coins)',
    home: 'Home',
    task: 'Task',
    invite: 'Invite & Earn',
    wallet: 'Wallet',
    menu: 'Menu',
    store: 'Adarsh Store',
    financial: 'Financial Products',
    investment: 'Pashudhan Project',
    supportHeading: 'We are ready to help you 24/7',
    supportContact: 'Customer Support',
    officeAddress: 'Office Address',
    quickLinks: 'Quick Links',
    privacyPolicy: 'Privacy Policy',
    termsConditions: 'Terms & Conditions',
    legalDisclaimer: 'Legal Disclaimer',
    withdrawHeader: 'Withdrawal',
    withdrawAmount: 'Amount to Withdraw',
    taxLabel: 'Govt Tax (5%)',
    finalReceive: 'You will receive',
    confirmBank: 'Confirm Bank Account',
    enterPinToConfirm: 'Enter PIN to confirm withdrawal',
    withdrawSuccess: 'Withdrawal request submitted successfully!',
  },
  hi: {
    welcome: 'प्रियादर्श में आपका स्वागत है',
    vision: 'हमारा दृष्टिकोण: हर भारतीय को वित्तीय स्वतंत्रता के साथ सशक्त बनाना।',
    services: 'सेवाएं: खरीदारी, निवेश, कार्य और बहुत कुछ।',
    register: 'पंजीकरण',
    login: 'लॉगिन',
    name: 'पूरा नाम',
    emailLabel: 'ईमेल पता',
    mobile: 'मोबाइल नंबर',
    referralId: 'रेफरर आईडी',
    referrerName: 'रेफरर का नाम',
    password: 'पासवर्ड (12 अंक)',
    pin: 'लेनदेन पिन (4 अंक)',
    deposit: 'जमा करें',
    balanceWallet: 'बैलेंस वॉलेट',
    coinWallet: 'कॉइन वॉलेट',
    redeem: 'रिडीम (50,000 कॉइन)',
    home: 'होम',
    task: 'कार्य',
    invite: 'आमंत्रित करें',
    wallet: 'वॉलेट',
    menu: 'मेनू',
    store: 'आदर्श स्टोर',
    financial: 'वित्तीय उत्पाद',
    investment: 'पशुधन परियोजना',
    supportHeading: 'हम आपकी मदद के लिए 24/7 तैयार हैं',
    supportContact: 'ग्राहक सहायता',
    officeAddress: 'कार्यालय का पता',
    quickLinks: 'त्वरित लिंक',
    privacyPolicy: 'गोपनीयता नीति',
    termsConditions: 'नियम और शर्तें',
    legalDisclaimer: 'कानूनी अस्वीकरण',
    withdrawHeader: 'निकासी',
    withdrawAmount: 'निकासी राशि',
    taxLabel: 'सरकारी कर (5%)',
    finalReceive: 'आपको प्राप्त होगा',
    confirmBank: 'बैंक खाते की पुष्टि करें',
    enterPinToConfirm: 'निकासी की पुष्टि के लिए पिन डालें',
    withdrawSuccess: 'निकासी अनुरोध सफलतापूर्वक सबमिट किया गया!',
  },
  gu: {
    welcome: 'પ્રિયાદર્શ સ્ટોરમાં આપનું સ્વાગત છે',
    vision: 'અમારું વિઝન: દરેક ભારતીયને આર્થિક સ્વતંત્રતા સાથે સશક્ત બનાવવું.',
    services: 'સેવાઓ: શોપિંગ, રોકાણ, કાર્યો અને વધુ.',
    register: 'રજીસ્ટર',
    login: 'લોગિન',
    name: 'પૂરું નામ',
    emailLabel: 'ઇમેઇલ એડ્રેસ',
    mobile: 'મોબાઈલ નંબર',
    referralId: 'રેફરર આઈડી',
    referrerName: 'રેફરરનું નામ',
    password: 'પાસવર્ડ (12 અંક)',
    pin: 'ટ્રાન્ઝેક્શન પિન (4 અંક)',
    deposit: 'ડિપોઝિટ',
    balanceWallet: 'બેલેન્સ વોલેટ',
    coinWallet: 'કોઈન વોલેટ',
    redeem: 'રીડીમ (50,000 સિક્કા)',
    home: 'HOME',
    task: 'કાર્ય',
    invite: 'ઈન્વાઈટ',
    wallet: 'વોલેટ',
    menu: 'મેનુ',
    store: 'આદર્શ સ્ટોર',
    financial: 'નાણાકીય ઉત્પાદનો',
    investment: 'પશુધન પ્રોજેક્ટ',
    supportHeading: 'અમે તમારી મદદ માટે ૨૪/૭ તૈયાર છીએ',
    supportContact: 'કસ્ટમર સપોર્ટ',
    officeAddress: 'ઓફિસ સરનામું',
    quickLinks: 'ક્વિક લિંક્સ',
    privacyPolicy: 'પ્રાઈવસી પોલીસી',
    termsConditions: 'ટર્મ્સ એન્ડ કન્ડિશન',
    legalDisclaimer: 'લીગલ ડિસ્ક્લેમર',
    withdrawHeader: 'વિડ્રોઅલ (ઉપાડ)',
    withdrawAmount: 'ઉપાડવાની રકમ',
    taxLabel: 'ગવર્મેન્ટ ટેક્સ (૫%)',
    finalReceive: 'તમારા ખાતામાં જમા થશે',
    confirmBank: 'બેંક ખાતાની પુષ્ટિ કરો',
    enterPinToConfirm: 'વિડ્રોઅલ કન્ફર્મ કરવા પીન નાખો',
    withdrawSuccess: 'વિડ્રોઅલ રિક્વેસ્ટ સફળતાપૂર્વક સબમિટ થઈ ગઈ છે!',
  }
};

export const PRODUCTS = [
  { id: '1', name: 'iPhone 15 Pro', category: 'Mobiles', image: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?w=400', link: 'https://amazon.in', price: '₹1,29,000' },
  { id: '2', name: 'Sony WH-1000XM5', category: 'Electronics', image: 'https://images.unsplash.com/photo-1648447226227-2dc0489567d4?w=400', link: 'https://amazon.in', price: '₹26,990' },
  { id: '3', name: 'Nike Air Jordan', category: 'Shoes', image: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=400', link: 'https://amazon.in', price: '₹12,495' },
  { id: '4', name: 'Premium Cotton Shirt', category: 'Clothes', image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400', link: 'https://amazon.in', price: '₹2,499' },
  { id: '5', name: 'Samsung Microwave', category: 'Home Appliances', image: 'https://images.unsplash.com/photo-1585659823160-3d2b302c55d7?w=400', link: 'https://amazon.in', price: '₹15,900' },
  { id: '6', name: 'Luxury Skincare Set', category: 'Beauty Care', image: 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400', link: 'https://amazon.in', price: '₹4,500' },
];

export const NAV_ITEMS = [
  { id: 'home', label: 'home', icon: <Home size={20} /> },
  { id: 'task', label: 'task', icon: <CheckSquare size={20} /> },
  { id: 'invite', label: 'invite', icon: <Users size={20} /> },
  { id: 'wallet', label: 'wallet', icon: <WalletIcon size={20} /> },
  { id: 'menu', label: 'menu', icon: <User size={20} /> },
];
